version: 0.1

phases:
  install:
    commands:
      - echo "Installing Nginx"
      - yum update -y || echo "YUM update failed, continuing anyway"
      - yum install nginx -y
  build:
    commands:
      - echo "Build Started On `date`""
      - cp index.html var/www/html
  post_build:
    commands:
      - echo "Configuring Nginx"

artifacts:
  files:
    - '**/*'