version: 0.1

phases:
  install:
    commands:
      - echo Installing Nginx
      - sudo amazon-linux-https disable
      - sudo yum update -y
      - sudo yum install nginx -y
  build:
    commands:
      - echo Build Started On `date`
      - cp index.html var/www/html
  post_build:
    commdans:
      - echo Configuring Nginx

artifacts:
  files:
    - '**/*'